# Generated by Django 4.2.6 on 2023-11-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_post_status_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
