# Generated by Django 4.2.6 on 2023-11-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_postcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_counter',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
